### PR TITLE
Add runtime.js optionally

### PR DESCRIPTION
**Pull request by vladtsf**

### CODE REVIEW

**Comment by phated** [comment]
Good idea.  Can you update the examples grunt.js file so they don't break on a recompile? Then I will merge. Thanks.

**Comment by vladtsf** [comment]
I've done! It's successfully recompiles now. Thanks

**Comment by phated** [comment]
Merged and published to NPM. Thanks for the PR, great option to have.

**Comment by vladtsf** [comment]
Thanks a lot!

**Pull request merged**
