### PR TITLE
Update version of jade.

### PR DESCRIPTION
**Pull request by mihneadb**
This brings supports for new features, like "rest arguments" in mixins. http://jade-lang.com/reference/mixins/

### CODE REVIEW

**Comment by phated** [comment]
This module is used by a small subset of the grunt + jade community and I don't know if it is worth it to bump and potentially break them.  Is there a reason you prefer to use this plugin over grunt-contrib-jade?

**Comment by mihneadb** [comment]
I just didn't know about it, why does it still exist if I should use grunt-contrib-jade? :)

**Comment by phated** [comment]
I am not going to unpublish something people rely on just because someone came in and created an alternative.  This module works for some people as it currently exists and I don't use grunt anymore.  I'm going to close this as grunt-contrib-jade is consistently updated and I consider this module to be `stability: locked`

**Comment by mihneadb** [comment]
Fair enough, thanks.

On Mon, Feb 16, 2015 at 9:16 PM, Blaine Bublitz notifications@github.com
wrote:

> I am not going to unpublish something people rely on just because someone
> came in and created an alternative. This module works for some people as it
> currently exists and I don't use grunt anymore. I'm going to close this as
> grunt-contrib-jade is consistently updated and I consider this module to be stability:
> locked
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/phated/grunt-jade/pull/24#issuecomment-74558640.

## 

Mihnea Dobrescu-Balaur

**Pull request closed without merging**
