### PR TITLE
Added 'locals' option, cleaned up the 'compile' helper a bit.

### PR DESCRIPTION
**Pull request by surjikal**
Before, the `options` object was passed as the locals. I've added an explicit `locals` option, which can be either a function or an object.

One thing to note: If someone was relying on the locals being the `options` object, he will have to update his config accordingly.

I'm not sure how to add an example for this option, as it would require its own jade file.

### CODE REVIEW

**Comment by phated** [comment]
I like this commit, but I don't plan to break the APIs until the 0.4 release.  I plan to make 0.4 work with grunt 0.3.x and bring in this feature this weekend.

**Comment by surjikal** [comment]
Sounds good!

**Comment by phated** [comment]
For 0.4, I am going to pass the options object to the template if locals doesn't exist.

**Comment by surjikal** [comment]
Oh good idea! In that case, you could even include it on master because it won't break the API.

**Comment by phated** [comment]
It still needs testing and I want to give it another once-over, but I think I will be able to release a 0.3.9 that keeps the old API and allows for the new API and these features.

If you get a chance, take a look at 0.3.9 - https://github.com/phated/grunt-jade/commits/0.3.9

**Pull request merged**
